name: test-github-workflow
run-name: ${{github.actor}} is regenerating default.pot

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-pot-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: "7.4"
      - run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - run: chmod +x wp-cli.phar
      - run: sudo mv wp-cli.phar /usr/local/bin/wp
      - run: wp i18n make-pot . languages/default.pot
      - run: git diff
