name: test-github-workflow
run-name: ${{github.actor}} is generating pot files 
on: [push]
jobs:
  run-pot-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php }} 
      - run: curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
      - run: chmod +x wp-cli.phar
      - run: sudo mv wp-cli.phar /usr/local/bin/wp
      - run: wp --info
