name: translation-workflow
run-name: regenerating pot file on translation branch

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  update-pot-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: "7.4"
      - name: Setup WP-CLI
        uses: godaddy-wordpress/setup-wp-cli@1
      # Create the translation branch if it doesn't exist
      - run: git branch | grep -q translation || git branch translation
      - run: git checkout translation
      - name: Merge master -> translation
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: translation
          github_token: ${{ github.token }}
      - run: wp i18n make-pot . languages/default.pot
      - name: push changes to translation branch
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: translation
          commit-message: 'update pot translation file'
